name: Update Gist

on:
  push:
    branch: master

  schedule:
    - cron: "* * * * *"

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        run: npm ci
      - name: Update gist
        run: node ./index.js
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 9cb3c9f7e8714ce1dc78df3dad40547f
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
